### ISSUE TITLE
1.19.3 Support

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [JustAHuman-xD/SlimefunEssentials#7]
Using the mod on 1.19.3 crashes giving an incompatible error.

**Comment by JustAHuman-xD** [comment]
When I'm done with school I'll make an updated version 👍

**Comment by pkstDev** [comment]
This is probably caused by EntityEmiStack, since 1.19.3 uses joml to provide Quaternion, in which vanilla had its own implementation. Also, registry is significantly changed. You can view the latest branch of EMITrades for an updated version of EntityEmiStack.

**Comment by JustAHuman-xD** [comment]
Released a version for 1.19.3!

**Comment by ghost** [comment]
Ayy epic!
